### ISSUE TITLE
Directus Credencials not working

### ISSUE THREAD

**Issue by inluxc** [nuxtus/nuxtus#1]
I just installed it with SQLite and the credentials are not working.

**Comment by craigharman** [comment]
Did you use the credentials that are at the bottom of the /server/.env file?

**Comment by craigharman** [comment]
@inluxc haven't heard back from you. Were you able to log in to Directus?

**Comment by inluxc** [comment]
Sorry, long weekend, yep I used the credentials in the file.

**Comment by bennyzen** [comment]
Same problem here. Following the guide you provide, I first tried using `admin@test.com` like indicated here.

![image](https://user-images.githubusercontent.com/13304/185739990-8a7bffab-ad8f-4508-aa7c-1977cae06b32.png)

This clearly should be `admin@example.com`.

**Comment by craigharman** [comment]
We've switched to using the directus default example `admin@example.com`. I'll update that file in the next release.
