### ISSUE TITLE
Wrong login? & simple misspelling.

### ISSUE THREAD

**Issue by jjaimealeman** [nuxtus/nuxtus#11]
I came across this project from the Directus Discord.

---

### Wrong Login
On https://docs.nuxtus.com/#/using-nuxtus it states:
> User: admin@example.com 👍
> Password: password

Which is accurate.

But upon launching http://localhost:3000/docs it incorrectly reads:
> Email: admin@test.com 👎
> Password: password

---

### Misspelling

One page `https://docs.nuxtus.com/#/cli?id=configuration` under **Configuration** it reads:
> this is done automatically for you if you are using the **_biolerplate_**

😆 Biolerplate/Boilerplate is misspelled.

---

I didn't have enough time to tinker any further tonight - but it looks promising!

**Comment by craigharman** [comment]
Thanks for the feedback. I've updated the included docs and fixed the typo both of which will be deployed next release.
