### ISSUE TITLE
Failed installing Directus: Error: Command failed: cd server && npm run cli bootstrap

### ISSUE THREAD

**Issue by slaanish** [nuxtus/nuxtus#16]
Windows 11

Running the installer fails with: 
`Failed installing Directus: Error: Command failed: cd server && npm run cli bootstrap`

![image](https://user-images.githubusercontent.com/1420293/188022745-e976ed40-c820-4c54-a16d-d3c7f51fa205.png)

Happy to provide any additional information.

**Comment by jjaimealeman** [comment]
There are two commands there `cd server` and `npm run cli bootstrap`.

Run the first one in your terminal inside of `C:\Projects\nuxtus`. I'm guessing it will fail there because as a Windows user, you do not have `cd` which is a Linux terminal command for 'Change Directory'. Unless you are running WSL? in which case `cd` will run, if it does run successfully, run the second command.

**Comment by slaanish** [comment]
Thanks for the quick reply.   The cd command does work fine on Windows, but it the command is running in the nuxtus directory, where I initiated the create command,  and the server directory is actually a folder deeper inside the created app directory.  

![image](https://user-images.githubusercontent.com/1420293/188033403-3f8b425e-2e73-4b81-8d3d-47b9b93771d2.png)



If I manually move to that directory and run:
`npm run cli bootstrap`
It fails with a sqllite error.  

![image](https://user-images.githubusercontent.com/1420293/188033847-856cf6c7-ae0e-4225-a2ea-9532fc6a1d8a.png)

This may be a windows issue if it has not been tested on windows.  Just thought I would let you know.  I will try and spin it up in WSL.  Thanks!

**Comment by craigharman** [comment]
Unfortunately, I don't have access to a Windows machine to test on but it seems to me the root cause is that the create script hasn't correctly identified the current working directory. 

I'll see if I can try this on a windows machine. But please update this ticket and let me know if WSL works.

**Comment by craigharman** [comment]
Got Windows 11 in a virtual desktop to test this. Thanks for reporting.

I just tried running `npx create-nuxtus test-app`  in `Windows Command Prompt` and everything installed okay. 

I then tried in `Windows Powershell` and got the same result.

![Image 2022-09-06 at 2 48 43 pm](https://user-images.githubusercontent.com/324026/188565813-193f8f3d-7f72-4034-ac63-b22738f44950.jpg)

I haven't used a Windows machine regularly for over 20 years so there might be something I'm missing, but the install script seems to work okay.

Node v16.17.0
Npm v8.15.0

Perhaps you could try updating Node version and re-run the installer?
I'll leave this ticket open for a few days and hope to hear back on how you went.

**Comment by slaanish** [comment]
That super interesting.  I just spun up a Windows 11 VM and installed node.  It failed again with the same error.  I am using the same versions of Nodejs and NPM as you did.

![image](https://user-images.githubusercontent.com/1420293/188640478-6a90a611-002f-480d-8792-6dc7cef2bc12.png)

After that failed, I got thinking it might be a path issue.  I moved it up a directory and ran it.  That passed.  I suspect an issue with using "nuxtus" in the path?  Thanks again for digging in.

![image](https://user-images.githubusercontent.com/1420293/188641508-9fe9e49b-f82b-4432-a394-e11c50a24315.png)

Here I used a string that does contain nuxtus.
![image](https://user-images.githubusercontent.com/1420293/188643400-949c60c2-4870-44b5-9e3e-58d19a7f68f9.png)

Here is one that does not contain nuxtus, but does nuxt.
![image](https://user-images.githubusercontent.com/1420293/188645831-92973d41-7c91-4936-a8d4-04bb2a1a21f5.png)

Here is one that has non nuxt containing string.
![image](https://user-images.githubusercontent.com/1420293/188652030-97d95161-2bd4-4ab5-8783-4de661678f44.png)


Hope this is helpful.  It appears to be the string "nuxt".

**Comment by craigharman** [comment]
Thank you for the updated information - this is very helpful! I'll look into it again in regards to the `nuxt` text in the directory and get back to you.

**Comment by craigharman** [comment]
It gets even weirder! I just tried the same combination of directories you did and everything worked for me!
Can you do me a favour and confirm if the sqlite database file is created in the successful vs failed installs and also check the `server/.env` file and send me the path of the sqlite database from that file?

**Comment by slaanish** [comment]
Directory contents: 
![image](https://user-images.githubusercontent.com/1420293/188885227-3e2e6d54-7a8f-4ca4-b917-15090f9c25cf.png)

.env contents:
![image](https://user-images.githubusercontent.com/1420293/188885365-52eecdfd-4fc3-42af-af2a-76f2656ac36e.png)

I think you are on to something.  The paths in the files look correct, but the sqlite file is missing in the path that contains the string nuxt.  Are you using the same casing?  I am at a loss at the moment.  It does work great otherwise, so I just wanted to say thanks for the cool project.

**Comment by craigharman** [comment]
Thanks for the kind words on the project, I'm glad you like it. I'm still at a loss as to why "nuxt" related folders don't work but I'm wondering if it is some form of permission issue. I'm working on another feature at the moment and will pop a couple of forced permission changes to the server folder and see if that helps you.

In the meantime, is the data.db file anywhere else in the directory structure? (Perhaps a folder up or something)?

**Comment by Intevel** [comment]
Im a windows user, currently im busy but after my appointment I can try to reproduce this. @craigharman

**Comment by craigharman** [comment]
That would be great thanks @Intevel! Appreciate any help narrowing this down.

**Comment by Intevel** [comment]
@craigharman Sorry, I can't reproduce this.
@slaanish Which Windows Build do you use?

**Comment by craigharman** [comment]
Wasn't able to reproduce this and no response in 2 months so I am going to close.
