### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by pvenableh** [nuxtus/nuxtus#49]
Any documentation/recommendations on deployment?  Looking into this and was wondering about how best to get a working version off my local machine and online.

**Comment by craigharman** [comment]
There are some initial steps for deployment here: https://docs.nuxtus.com/deployment.html

However these are pretty broad and I want to develop some more specific instructions. What kind of project are you looking at deploying (eg. SPA? Server rendered? Static?) and perhaps I can assist with some more detail.

**Comment by pvenableh** [comment]
Hey @craigharman.  I have been using Nuxt for a few years as well as Directus.  In the process of migrating to Nuxt 3 and Directus 9...trying to find the best deployment options for SSR.  I've used DigitalOcean Apps...Netlify with Nuxt 3....I would love to have the Nuxtus structure live with a domain - with Directus live on a subdomain.  Do you have a live example of Nuxtus deployed with a domain?   What have you used?  

Appreciate any input on this.

**Comment by craigharman** [comment]
The nuxtus site itself (https://www.nuxtus.com/) does this. Static site hosted with Netlify - currently I have a local Directus install that builds to static site but this also could be hosted somewhere - including the Directus Cloud platform if you wish (you'd just need to [manually set up the flows](https://docs.nuxtus.com/directus-cloud.html) for this).
