### ISSUE TITLE
Can't create Nuxtus Project

### ISSUE THREAD

**Issue by bastianhilton** [nuxtus/nuxtus#57]
I'm getting this error while attempting to create a sample Nuxtus project: Failed cloning Nuxtus repo: Error: Command failed: git clone --depth 1 -b main https://github.com/nuxtus/nuxtus C:\Users\login\Documents\Nuxt-Projects\SampleProjects\nuxtusSample.

I'm running Windows 11
Directus is hosted on my AWS Lightsail docker instance
RDS Postgres Instance on AWS.

**Comment by craigharman** [comment]
Assume this is during the `npx create-nuxtus` step? Are you able to include your full output?

**Comment by craigharman** [comment]
No response so closing.
