### ISSUE TITLE
Failed installing Directus:

### ISSUE THREAD

**Issue by jjaimealeman** [nuxtus/nuxtus#58]
![image](https://user-images.githubusercontent.com/1428292/235826204-e4302d17-f503-4d38-9988-e2bd751b59de.png)

```
node v.16.18.0
npm 8.19.2
```

😥

**Comment by jjaimealeman** [comment]
I gave it another try, this time with supabase data.

![image](https://user-images.githubusercontent.com/1428292/235828562-123f4ee9-7e72-45c8-965c-f78fcbdf12e4.png)

**Comment by craigharman** [comment]
Hmmmm... interesting. Does that file `env-stub.liquid` exist in the given path?

**Comment by jjaimealeman** [comment]
Negative Sir. Only these 4 files exist.

```
.
├── env-directus.liquid
├── env-nuxt.liquid
├── gitignore.liquid
└── package.json.liquid
```

**Comment by craigharman** [comment]
env-stub doesn't exist in the more recent versions of Nuxtus. Can you try `npm list -g` and check that you have the latest version?
