### ISSUE TITLE
Cannot read properties of undefined (reading 'authDirectus')

### ISSUE THREAD

**Issue by bastianhilton** [nuxtus/nuxtus#70]
After installing the plugin and following the directions on the website for this plugin, I get this error message when starting up my nuxt project. 

Steps I took:

1.  Install Nuxtus plugin in Directus using pnpm install "plugin"
2. Install Nuxtus plugin in Nuxt 3 project
3. Start up Nuxt project and error message appears.

I didn't add any configuration options other than the .env variables.

**Comment by craigharman** [comment]
Can you try adding the following to `nuxt.config.ts`:

```ts
runtimeConfig: {
		nuxtus: {
			directus: {
				email: process.env.NUXTUS_DIRECTUS_ADMIN_EMAIL,
				password: process.env.NUXTUS_DIRECTUS_ADMIN_PASSWORD,
				token: process.env.NUXTUS_DIRECTUS_STATIC_TOKEN || null,
			},
		},
		public: {
			nuxtus: {
				authDirectus: process.env.NUXTUS_DIRECTUS_AUTH === "true",
				directus: {
					url: process.env.DIRECTUS_URL || "http://localhost:3000",
				},
			},
		},
	},
```

**Comment by craigharman** [comment]
Have added this to the documentation: https://docs.nuxtus.com/installation.html#existing-project
