### ISSUE TITLE
Issue with plugin and nuxt.config.js setup

### ISSUE THREAD

**Issue by bastianhilton** [nuxtus/nuxtus#75]
I have this setup in my nuxt.config.js

runtimeConfig: {
 	nuxtus: {
 		directus: {
 			email: process.env.NUXTUS_DIRECTUS_ADMIN_EMAIL,
 			password: process.env.NUXTUS_DIRECTUS_ADMIN_PASSWORD,
 			token: process.env.NUXTUS_DIRECTUS_STATIC_TOKEN || null,
 		},
 	},
 	public: {
 		nuxtus: {
 			authDirectus: process.env.NUXTUS_DIRECTUS_AUTH === "true",
 			// If you are not using Nuxt SSR then these credentials will be public, give user read one access
 			directus: {
 				url: process.env.DIRECTUS_URL || "http://localhost:3000",
 			},
 		},
 	},
 },

but I get the error cannot redefine $directus.

when I update this to something like this:

public: {
      nuxtus: {
				authDirectus: process.env.NUXTUS_DIRECTUS_AUTH === "true",
				directus: {
					url: process.env.DIRECTUS_URL,
          email: process.env.NUXTUS_DIRECTUS_ADMIN_EMAIL,
          password: process.env.NUXTUS_DIRECTUS_ADMIN_PASSWORD,
          token: process.env.NUXTUS_DIRECTUS_STATIC_TOKEN || null,
				},
			},
    },

within the runtimeConfig then it gives this error Cannot read properties of undefined (reading 'directus')

If I remove the the directus part under public and just keep the nuxtus: part at the top then it says url isn't defined.

No matter what I try it provides errors. Any idea how to fix this?

P.S. i'm using the existing installation steps.

**Comment by craigharman** [comment]
What version of Nuxtus and Nuxt are you using?

**Comment by bastianhilton** [comment]
nuxtus: 2.9.0
nuxt: latest

**Comment by craigharman** [comment]
Hmmmm. The `directus` property in the config should be safe as it is defined within a `nutxus` property so I can't imagine the $directus error being a conflict.

A couple of things to confirm:

1. Are you using any other Directus related plugins - in particular the Nuxt Directus one? This has been removed in the latest version of Nuxtus in favour of the SDK. You may have to remove this.
2. Try creating a new install of Nuxtus separately and use the generated config and see if you can work out any differences.

**Comment by bastianhilton** [comment]
Following this step here in the guide: https://docs.nuxtus.com/installation.html

Are you saying that step 1 isn't needed? Which means I dont' have to install the directus extension within Directus, because I did.

Also I didn't install Nuxtus project just the plugin into my existing project, this is the runtimeConfig

runtimeConfig: {
    websiteURL: process.env.GQL_HOST,
    websiteToken: process.env.WEBSITE_TOKEN,
    turnstile: {
      // This can be overridden at runtime via the NUXT_TURNSTILE_SECRET_KEY
      // environment variable.
      secretKey: process.env.NUXT_TURNSTILE_SECRET_KEY,
    },
    nuxtus: {
      directus: {
        email: process.env.NUXTUS_DIRECTUS_ADMIN_EMAIL,
        password: process.env.NUXTUS_DIRECTUS_ADMIN_PASSWORD,
        token: process.env.NUXTUS_DIRECTUS_STATIC_TOKEN || null,
      },
    },
    public: {
      stripePk: process.env.STRIPE_PUBLIC_KEY,
      nuxtus: {
        authDirectus: process.env.NUXTUS_DIRECTUS_AUTH === "true",
        // If you are not using Nuxt SSR then these credentials will be public, give user read one access
        directus: {
          url: process.env.DIRECTUS_URL,
        },
      },
    },
  },

**Comment by craigharman** [comment]
Also can you please [format your code/config](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) when you paste it into the comments, it makes it much easier to read and parse.

**Comment by bastianhilton** [comment]
Apologies, yes I do have the Nuxt Directus plugin installed

**Comment by craigharman** [comment]
I think the error you may be getting is from Nuxt Directus rather than Nuxtus. If you have just copy and pasted our runtime config then you are missing the Nuxt Directus config which also requires a directus value. Refer to their [docs here](https://www.nuxt-directus.site/getting-started/setup). You will need to combine the configs if you wish to use both. Alternatively if you will move to Nuxtus, then we use the Directus SDK so you could use that and remove the Nuxt Directus requirement.

**Comment by bastianhilton** [comment]
i removed the nuxt-directus module from my install and just kept the directus sdk.

**Comment by craigharman** [comment]
Great, glad you solved your issue.
